### ISSUE TITLE
Setup error

### ISSUE THREAD

**Issue by oliverbienert** [fixate/generator-fixate-pw#30]
Hi guys,

I get an error when trying to follow your instructions:

```
oliver@oliver-R540:~/workspaces/webapps/fixate-pw$ yo fixate-pw
undefined
? Which branch of ProcessWire would you like to use? master
? Which branch of the CSS Framework would you like to use? inuit
? What is the domain name for the production website (without protocol)? example.com
? Which ProcessWire modules would you like to install? ProcessRedirects, MarkupSimpleNavigation, MarkupSitemapXML, ProcessWireUpgrade
     info Installing ProcessWire...
     info Copying ProcessWire install...
/home/oliver/Apps/generator-fixate-pw/app/templates/.gitcache/ryancramerdesign/ProcessWire /home/oliver/workspaces/webapps/fixate-pw
From https://github.com/ryancramerdesign/ProcessWire
 * branch            master     -> FETCH_HEAD
Already up-to-date.
Already on 'master'
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: write after end
    at writeAfterEnd (_stream_writable.js:167:12)
    at WriteStream.Writable.write (_stream_writable.js:214:5)
    at Socket.ondata (_stream_readable.js:540:20)
    at Socket.emit (events.js:129:20)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at Pipe.onread (net.js:538:20)
shell.js: internal error
Error: Command failed: "/usr/bin/nodejs" /tmp/shelljs_4f9efba9bf78a1fa6e71
  at checkExecSyncError (child_process.js:1346:13)
  at Object.execSync (child_process.js:1386:13)
  at execSync (/home/oliver/Apps/generator-fixate-pw/node_modules/shelljs/src/exec.js:77:11)
  at Object._exec (/home/oliver/Apps/generator-fixate-pw/node_modules/shelljs/src/exec.js:210:12)
  at Object.exec (/home/oliver/Apps/generator-fixate-pw/node_modules/shelljs/src/common.js:182:23)
  at Function.GitUtils.exec (/home/oliver/Apps/generator-fixate-pw/app/lib/git-utils.coffee:19:14)
  at Function.GitUtils.export (/home/oliver/Apps/generator-fixate-pw/app/lib/git-utils.coffee:28:14)
  at /home/oliver/Apps/generator-fixate-pw/app/generator.coffee:107:7
  at FixatePwGenerator.module.exports.FixatePwGenerator.app (/home/oliver/Apps/generator-fixate-pw/app/generator.coffee:236:5)
  at /home/oliver/Apps/generator-fixate-pw/node_modules/yeoman-generator/lib/base.js:409:16
  at processImmediate [as _immediateCallback] (timers.js:367:17)

```

I'm quite new in the npm world so if you have any hints?

Cheers Oliver

**Comment by larrybotha** [comment]
Hi @oliverbienert - I could recreate this locally, seems like shelljs somehow became unhappy with something. How specific :package: 

Anyhoo, I've updated the shelljs version in package.json, and rerun the generator, and everything is working as expected (apart from bower and npm install not running at the end).

Do the following and let me know if I should open up this ticket again:

- get the latest version of the generator (not sure if yeoman will let you do this, or if you should do a git pull inside your clone)
- run `npm install`
- try run the generator again

After the install you'll need to run bower and npm in your project folder manually:
```shell
$ npm install && bower install
```

Let me know how it goes!

**Comment by oliverbienert** [comment]
Hi Larry,

sorry for being soooo late..

I am a part time musician and was on tour with a band.

Anyway, I'll try as you suggested and will report either success or failure.

Cheers Oliver

**Comment by oliverbienert** [comment]
Hi,

I cloned your rep again and came a bit closer, however, I still have  questions/problems.

After cloning, I run `sudo npm link` and `sudo npm install`.

Each command printed a warning:
`npm WARN EPEERINVALID generator-fixate-pw@0.2.19 requires a peer of yo@>=1.0.0 but none was installed.`

When I do a `npm list -g yo`, I get Version 1.5

`yo fixate-pw` got through, though.

But now I stumbled about the line which says _Install Processwire_.
It's not quite clear what to do for me here. I tried and setup an Apache virtualhost and run `<hostname>/src`
But processwire complains. The site directory is quite incomplete or so it seems. There is just an assets subdir, nothing else.
How is that supposed to work?

Regards Oliver

**Comment by larrybotha** [comment]
the directory should look as follows after yeoman completes (you'll likely have to run `npm install && bower install` manually - not sure why it doesn't run):

```bash
├── database
│   ├── dev
│   └── prod
├── gulpconfig.json
├── gulpfile.coffee
├── package.json
├── secrets-sample.json
├── secrets.json
├── setup.js
├── src
│   ├── COPYRIGHT.txt
│   ├── LICENSE.txt
│   ├── htaccess.txt
│   ├── humans.txt
│   ├── index.php
│   ├── install.php
│   ├── robots.txt
│   ├── site
│   └── wire
└── styleguide
    ├── README.md
    ├── gulpfile.js
    ├── package.json
    ├── src
    └── webpack.config.js
```

Are you not getting this structure?

Once pointing your virtualhost to your `./src` folder, you should be able to visit the `/install` at the domain you specify in your virtualhost.

Do you have any luck when starting a PHP server from the `src/` folder?

```bash
$ php -S localhost:8000
```

I've pushed a new update, so try pulling the generator down again, and giving it another go.

Let me know if the generator isn't building as above (I had to run the generator twice a few minutes ago when erroring on the CSS framework).

**Comment by larrybotha** [comment]
@oliverbienert whoops - I missed that you were talking specifically about `src/site/` containing only `assets`.

Take a bash at updating the generator on your side.

With a fresh generate you should see the following structure in `src/site`:

```bash
├── site
│   ├── assets
│   ├── config.php
│   ├── install
│   ├── modules
│   └── templates
```

**Comment by oliverbienert** [comment]
Hi there,

after updating the generator I was able to install processwire.
Some issues remain, still:

* On the command line, I get the hint that I should run `npm install & bower install`. It should read: `npm install && bower install`, with a double '&&', shouldn't it?
* When I start a web-server by `php -S localhost:8000`, processwire complains that it needs _mod\_rewrite_, so I think I have to use Apache.
* Running gulp throws an error, because your *errorHandler*-function is defined as `handleError`.
* Before running `gulp`, as stated in the readme, I had to run the `build` task to create the minified files.  

I also had to run `build` to create some minified files. But what happens here, is not fully clear to me. Some files are created in a folder *public*, some in *assets*. When I look at the page with firebug, several files are missing, though:
* assets/js/main.min.js
* assets/img/logo.svg
* fnt/%5Bfon-folder%5D/%5Bfont-file-name-without-extension%5D.woff2
* assets/public/fnt/%5Bfon-folder%5D/%5Bfont-file-name-without-extension%5D.woff
* assets/public/fnt/%5Bfon-folder%5D/%5Bfont-file-name-without-extension%5D.ttf

There are some bracket's in the font paths that doesn't get substituted.
I'm quite sure I miss some configuration?

Regards Oliver

**Comment by larrybotha** [comment]
> On the command line, I get the hint that I should run npm install & bower install. It should read: npm install && bower install, with a double '&&', shouldn't it?

This is yeoman's recommendation. A single `&` means it will run concurrently with the previous commands - `&&` waits for a truish response from the previous command before running the subsequent command.

> When I start a web-server by php -S localhost:8000, processwire complains that it needs mod_rewrite, so I think I have to use Apache.

My bad! I should have thought about that when suggesting it. Yup, you'll have to use Apache to serve ProcessWire

> Running gulp throws an error, because your errorHandler-function is defined as handleError.

Thanks for that - it's been updated in the generator: https://github.com/fixate/generator-fixate-pw/commit/820c29957adc92c49b52ea9c3386201144f861f2

---

You shouldn't run `$ gulp build` to begin any work. 

Running `$ gulp` will start watchers, allowing you to begin updating scss and js / coffee. Make sure to add your vhost to `bsProxy` in secrets.json - this will give you live-reloading with BrowserSync.

`$ gulp build` task prepares a few things to get your site ready for production:

- minifies js, css, svgs
- revs assets with MD5 hashes for cache busting e.g. style-a3ea3ea4e2tjl.css
  - js
  - css
  - fonts
  - images
- writes rev-manifest.json for the PW MVC Boilerplate to correctly output rev'd assets into the document (take a look at the assets on http://nuclearmed.co)

The boilerplate will check if your rev-manifest.json has an associated rev'd asset, and will output that into your site, otherwise it will output the minified asset without the rev.

By adding `$config->debug = true` to your `config-dev.php` the boilerplate will automatically keep your local site in dev mode, serving non-minified assets: https://github.com/fixate/pw-mvc-boilerplate/blob/master/config/boot.php#L25

You can force production mode locally by uncommenting `'env' => 'production'` in [custom/environment.php](https://github.com/fixate/pw-mvc-boilerplate/blob/master/config/environment.php#L11).

---

> assets/js/main.min.js

The MVC boilerplate has `$this->js_add_script('main');` on line 9. This has been updated to use `built`: https://github.com/fixate/pw-mvc-boilerplate/commit/9abf6cae97d32af0677eb28e7b784dd82c7dace7

---

> assets/img/logo.svg

This is a sort of placeholder in meta.html.php: https://github.com/fixate/pw-mvc-boilerplate/blob/master/views/partials/meta.html.php#L27

This is 404'ing because you don't yet have `logo.svg`. You can either remove this meta tag from your project, or update it to point to an svg logo for the project.

---

> fnt/%5Bfon-folder%5D/%5Bfont-file-name-without-extension%5D.woff2
> assets/public/fnt/%5Bfon-folder%5D/%5Bfont-file-name-without-extension%5D.woff
> assets/public/fnt/%5Bfon-folder%5D/%5Bfont-file-name-without-extension%5D.ttf

These assets are 404'ing as they are placeholders for the final values you want to add to your project. I have updated the comments on that project, with the relevant files: 
https://github.com/larrybotha/styleguide/blob/inuit/scss/custom/_config.scss#L110-L141
https://github.com/larrybotha/styleguide/blob/inuit/scss/custom/base/_fonts.scss

[custom/base/_fonts.scss](https://github.com/larrybotha/styleguide/blob/inuit/scss/custom/base/_fonts.scss) is specifically for custom fonts. If you only need system fonts, you can comment out those mixins, and remove the references to any specific font files in [custom/_config.scs](https://github.com/larrybotha/styleguide/blob/inuit/scss/custom/_config.scss#L110-L141)

Let me know how you get along!
